### ISSUE TITLE
Onchain reading from layer 1

### ISSUE THREAD

**Issue by pikonha** [blockful-io/external-resolver#14]
# Feature Request

We should be able to read data from the native layer 1 ENS solution. This will be the foundation for the future offchain implementations.

## Describe Preferred Solution

The client needs to be able to call the Registry for getting the given domain's Resolver for then to read its properties stored onchain.

```mermaid
sequenceDiagram
    Client->>Registry: resolver("test.eth")
    Registry->>Client: L1 Contract address
    Client->>L1 Contract: resolve("test.eth")
    L1 Contract->>Client: 0x....
```

## Additional Context

The reading should be pretty straightforward giving that the SDKs support the layer 1 reading and writing by default.

## Related Code

* [Viem reading implementation](https://viem.sh/docs/ens/actions/getEnsName.html)
* [Ethers reading implementatio](https://docs.ethers.org/v6/api/providers/ens-resolver/#EnsResolver)

Blocked by #11

**Comment by LeonardoVieira1630** [comment]
Solved in #11
