### ISSUE TITLE
[L2] Create contract for Optimism reading 

### ISSUE THREAD

**Issue by pikonha** [blockful-io/external-resolver#16]
# Feature Request

We need to have an smart contract deployed on any given layer 2 protocol to be used as an external source which will be used on the redirecting phase of the L1 flow.

```mermaid
sequenceDiagram
  Client->>Registry :resolver("test.eth")
  Registry->>Client :0x....
  Client->>Resolver :setText("test.eth", "avatar", "avatar.png")
  Resolver->>Client :revert `StorageHandledByL2(chainId, contractAddress)`
  Client->>⭐ L2 Contract :setText("test.eth", "avatar", "avatar.png")
```

## Describe Preferred Solution

The L2 contract should behave exactly the same way as [Public Resolver](https://docs.ens.domains/resolvers/interfaces) would in the Layer 1.

[Address reading implementation](https://github.com/ensdomains/ens-contracts/blob/master/contracts/resolvers/profiles/AddrResolver.sol#L35)

```solidity
/**
    * Returns the address associated with an ENS node.
    * @param node The ENS node to query.
    * @return The associated address.
    */
function addr(
    bytes32 node
) public view virtual override returns (address payable) {
    bytes memory a = addr(node, COIN_TYPE_ETH);
    if (a.length == 0) {
        return payable(0);
    }
    return bytesToAddress(a);
}
```

## Checklist

- [ ] Deploy contract on L2
- [ ] Set L2 contract address on L1 contract

## Related Code

[Public Resolver contract implementation](https://github.com/ensdomains/ens-contracts/blob/master/contracts/resolvers/PublicResolver.sol)
[Offchain Resolving](https://docs.ens.domains/resolvers/ccip)
[Address reading implementation](https://github.com/ensdomains/ens-contracts/blob/master/contracts/resolvers/profiles/AddrResolver.sol#L35)

## Additional Context

After being deployed to the given layer 2, the contract address should be stored in the layer 1 contract in order to redirect the requests by using `StorageHandledByL2(chainID, contractAddress)`.

**Comment by LeonardoVieira1630** [comment]
Canceled because the ENS is implementing some modifications on the contracts related to Opitimism.
