### ISSUE TITLE
Create contract for Gateway reading and writing

### ISSUE THREAD

**Issue by pikonha** [blockful-io/external-resolver#17]
# Feature Request

The ENS storage of properties related to a domain or subdomains can be handled by Offchain gateway, an API that exposes a REST endpoint (see below) and saves its content into a data source that can be pretty much anything.

## Describe Preferred Solution

The Gateway should expose a REST endpoint that follows either of the following patterns as defined in [ERC-3668](https://eips.ethereum.org/EIPS/eip-3668#gateway-interface):

- GET `/{sender}/{data}.json`
- POST `/{sender}.json` body: `{data}`

```mermaid
sequenceDiagram
  Client->>Registry :resolver("test.eth")
  Registry->>Client :0x....
  Client->>Resolver :resolve("test.eth")
  Resolver->>Client :revert `StorageHandledByOffchainDatabase(sender, url, calldata)`
  Client->>Gateway :GET `/{sender}/{data}.json`
  Gateway->>Client :200 OK
```

- The `sender` is the smart contract address and its version.
- The `url` is the Gateway's URL so the Client can redirect the request
- The `calldata` is the encoded information of the domain such as owner address, namehash, and parameters

[Smart contract implementation](https://eips.ethereum.org/EIPS/eip-5559#example-1)

```solidity
function setAddr(bytes32 node, address a) external {
    IWriteDeferral.parameter[] memory params = new IWriteDeferral.parameter[](3);

    params[0].name = "node";
    params[0].value = BytesToString.bytes32ToString(node);

    params[1].name = "coin_type";
    params[1].value = Strings.toString(coinType);

    params[2].name = "address";
    params[2].value = BytesToString.bytesToString(a);

    revert StorageHandledByOffChainDatabase(
        IWriteDeferral.domainData(
            {
                name: WRITE_DEFERRAL_DOMAIN_NAME,
                version: WRITE_DEFERRAL_DOMAIN_VERSION,
                chainId: 1,
                verifyingContract: address(this)
            }
        ),
        _offChainDatabaseUrl,
        IWriteDeferral.messageData(
            {
                functionSelector: msg.sig,
                sender: msg.sender,
                parameters: params,
                expirationTimestamp: block.timestamp + _offChainDatabaseTimeoutDuration
            }
        )
    );
}
```

## Describe Alternatives

The `/{sender}/{data}.json` is a pattern created for reading data offchain, which doesn't necessarily attend to the writing requirements. If so, a new pattern could be created and applied as a new EIP, giving that the EIP-5559 is still under discussion in the community.

## Related Code

[Smart contract implementation](https://eips.ethereum.org/EIPS/eip-5559#example-1)

## Additional Context

No offchain writing implementation has been found so far.

**Comment by LeonardoVieira1630** [comment]
Solved in #10 .
