### ISSUE TITLE
[L2] Call l2 on gateway

### ISSUE THREAD

**Issue by pikonha** [blockful-io/external-resolver#20]
# Feature Request

We need to have an smart contract deployed on any given layer 2 protocol to be used as an external source which will be used on the redirecting phase of the L1 flow.

```mermaid
sequenceDiagram
  Client->>Registry :resolver("test.eth")
  Registry->>Client :0x....
  Client->>Resolver :text("test.eth", "avatar", "avatar.png")
  Resolver->>Client :revert `StorageHandledByL2(chainId, contractAddress)`
  Client->> L2 Contract :text("test.eth", "avatar", "avatar.png")
```

## Describe Preferred Solution

The client should be able to:

1. Connect to L2
2. Call the given method on the L2 contract
3. Return response

To complete this issue, it is be necessary the following steps:
- [x] L2 gateway file.
- [x] L2 repository class.
- [x] Script to deploy on arbitrum  L1.
- [x] Script to deploy on arbitrum L2.
- [x] Resolver contract for arbitrum on layer 2.
- [x] Get functions implemented. 

## Related Code

[Public Resolver contract implementation](https://github.com/ensdomains/ens-contracts/blob/master/contracts/resolvers/PublicResolver.sol)
[Offchain Resolving](https://docs.ens.domains/resolvers/ccip)
[Address reading implementation](https://github.com/ensdomains/ens-contracts/blob/master/contracts/resolvers/profiles/AddrResolver.sol#L35)
[Read data validation](https://github.com/wevm/viem/blob/main/src/utils/ccip.ts#L78)

## Additional context

No implementation of the CCIP-Read on Layer 2 has been found so far. The most popular JS libraries ([Viem](viem.sh) and [Ethers](https://docs.ethers.org/v6/)) currently only support the Gateway reading.

We're not sure about whether the L2 response validation on L1 will be made through the callback (e.g. `resolveWithProof`) or via [Merkle Proof](https://medium.com/crypto-0-nite/merkle-proofs-explained-6dd429623dc5).

**Comment by pikonha** [comment]
blocked by #51

**Comment by jxom** [comment]
> No implementation of the CCIP-Read on Layer 2 has been found so far. 

Viem supports CCIP-Read. Any `eth_call` which calls a contract that reverts with an `OffchainLookup` selector will perform the expected CCIP-Read behavior.
