### ISSUE TITLE
Implement offchain reading from Gateway on Client

### ISSUE THREAD

**Issue by pikonha** [blockful-io/external-resolver#21]
# Feature Request

We need to have an API that is compliant to the [ENS' Gateway Interface](https://eips.ethereum.org/EIPS/eip-3668#gateway-interface) to be used as an external source which will be used on the redirecting phase of the L1 flow.

```mermaid
sequenceDiagram
  Client->>Registry :resolver("test.eth")
  Registry->>Client :0x....
  Client->>Resolver :text("test.eth", "avatar")
  Resolver->>Client :revert StorageHandledByOffchainDatabase(sender, url, message)
  Client->>Gateway :GET /{sender}/{encode(text("test.eth", "avatar"))}.json
  Gateway->>Client :200 ok {response}
  Client->>Resolver :callback(response, message.callbackData)
```

## Describe Preferred Solution

The [ERC-3668 specification](https://eips.ethereum.org/EIPS/eip-3668) requires the read data from any offchain data source to be validated on the layer 1 by calling a callback function with the Gateway's response and the `callbackData`.

[Client read and callback validation](https://github.com/wevm/viem/blob/main/src/utils/ccip.ts#L78):

```js
const result = await ccipFetch({ data: callData, sender, urls }) // Gateway call

const { data: data_ } = await call(client, { // L1 data validation
  blockNumber,
  blockTag,
  data: concat([
    callbackSelector,
    encodeAbiParameters(
      [{ type: 'bytes' }, { type: 'bytes' }],
      [result, extraData],
    ),
  ]),
  to,
} as CallParameters)

return data_!
```

[Layer 1 data validation](https://github.com/ensdomains/offchain-resolver/blob/main/packages/contracts/contracts/OffchainResolver.sol#L57):
```solidity
/**
* Callback used by CCIP read compatible clients to verify and parse the response.
*/
function resolveWithProof(bytes calldata response, bytes calldata extraData) external view returns(bytes memory) {
    (address signer, bytes memory result) = SignatureVerifier.verify(extraData, response);
    require(
        signers[signer],
        "SignatureVerifier: Invalid sigature");
    return result;
}
```

## Checklist

- [ ] Call L1 Registry: `resolver("test.eth")`
- [ ] Call L1 Resolver: `text("test.eth", "com.twitter")`
- [ ] Handle `StorageHandledByOffchainDatabase(sender, url, message)` error
- [ ] Call Gateway: GET `/{sender}/{encode(text("test.eth", "com.twitter"))}.json`
- [ ] Validate response on L1 Resolver: `callback(response, callbackData)`

## Related Code

[Public Resolver contract implementation](https://github.com/ensdomains/ens-contracts/blob/master/contracts/resolvers/PublicResolver.sol)
[Offchain Resolving](https://docs.ens.domains/resolvers/ccip)
[Address reading implementation](https://github.com/ensdomains/ens-contracts/blob/master/contracts/resolvers/profiles/AddrResolver.sol#L35)
[Read data validation](https://github.com/wevm/viem/blob/main/src/utils/ccip.ts#L78)

**Comment by LeonardoVieira1630** [comment]
Duplicated by #20
