### ISSUE TITLE
[L2] Read ENS properties from L2 on gateway

### ISSUE THREAD

**Issue by LeonardoVieira1630** [blockful-io/external-resolver#23]
# Feature Request

After implementing the _read information from a layer 2_ feature, it will be necessary to create some integration tests. The tests will be responsibly to ensure that the flow of interaction between each part of the project is working properly and test bad scenarios to see how the code handles it.

## Describe Preferred Solution

To complete this issue, it is be necessary the following tests:
- [ ] Main flow of reading information from layer 2 as specified in the image at the additional context;
- [ ] Flow with a error in the final validation step;
- [ ] Contract's address not exist; 
- [ ] Wrong calls in the resolver contract;

## Additional Context

The right expected flow of interactions is the following one: 

<img width="870" alt="Captura de Tela 2024-02-23 às 14 50 21" src="https://github.com/blockful-io/external-resolver/assets/69486932/7e51775e-34d4-4338-b99a-850c3ff065ba">

**Comment by pikonha** [comment]
duplicated by #20
