### ISSUE TITLE
Integration tests for writing (Layer 2)

### ISSUE THREAD

**Issue by LeonardoVieira1630** [blockful-io/external-resolver#26]
# Feature Request

After implementing the _write information on a Layer 2_ feature, it will be necessary to create some integration tests. The tests will be responsibly to ensure that the flow of interaction between each part of the project is working properly and test bad scenarios to see how the code handles it.

## Describe Preferred Solution

To complete this issue, it is be necessary the following tests:
- [ ] Main flow of writing information on the Layer 2 as specified in the image at the additional context;
- [ ] Contract's address not exist; 
- [ ] Wrong calls in the resolver contract;

## Additional Context

The right expected flow of interactions is the following one: 

<img width="855" alt="Captura de Tela 2024-02-23 às 15 24 17" src="https://github.com/blockful-io/external-resolver/assets/69486932/8e30b2d4-bbb0-4c4d-8712-457b4eb55ccb">

**Comment by pikonha** [comment]
blocked by #83
