### ISSUE TITLE
Integration tests (core)

### ISSUE THREAD

**Issue by LeonardoVieira1630** [blockful-io/external-resolver#30]
# Feature Request

Implement an integrated test for the project, aiming to integrate the existing components: Client, Gateway, Registry Contract on layer 1 (L1), and the Offchain-Resolver Contract, also from layer 1. This test is designed to establish the complete flow of interactions between these components, serving as a solid foundation for future integrated tests.

## Describe Preferred Solution

Develop a comprehensive integrated test script, preferably written in TypeScript, that will act as a client and perform the following actions:

- [x] Start the server (gateway).
- [x] Deploy the contracts (registry and resolver).
- [x] Make a call to the registry and receive the callback with the resolver's address.
- [x] Make a call to the resolver and receive the callback with the offchain address of the gateway.
- [x] Make a call to the gateway.

This script should effectively simulate the end-to-end flow of interactions between the specified components, validating their integration and ensuring a comprehensive understanding of the system's functionality.

## Related Code

- [External Resolver Repository](https://github.com/ensdomains/offchain-resolver): This repository contains the structure of the Resolver that should be utilized for integration.
- [Example E2E Test](https://github.com/ensdomains/offchain-resolver/blob/main/packages/gateway-worker/test/e2e.test.ts): Here, you can find an example of an end-to-end test using the specified contract. This can serve as a reference for implementing the integrated test in your project.
- [EVM Gateway Repository](https://github.com/ensdomains/evmgateway): This repository contains the implementation of a gateway and some tests that can serve as inspiration for your project.

**Comment by pikonha** [comment]
no need for testing what is developed by the ENS DAO, it would be a huge rework with way too little value
