### ISSUE TITLE
refactor: integration tests to use vitest instead jest

### ISSUE THREAD

**Issue by LeonardoVieira1630** [blockful-io/external-resolver#46]
### Describe the Refactor Request

In the integration tests branch, it was used jest. Otherwise, in some parts of the project, it is being used vitest, that is newer and more performative. 
So, to make a more concise and more performative code, the integration tests need to be refactored.

### Describe Preferred Solution
To complete the issue, the integration test needs to import vitest functions and definitions, like beforeAll, it and describe. None of jest definitions will be used after the modification. 

### Related Code
An example of test the is using the vitest already can be seen at: https://github.com/blockful-io/external-resolver/blob/integrationTests/packages/client/test/public.test.ts

### Additional Context

vitest docs: https://vitest.dev/guide/

**Comment by pikonha** [comment]
is there a PR for this?
