### ISSUE TITLE
[SPIKE] Validate read data from L2 part 2

### ISSUE THREAD

**Issue by LeonardoVieira1630** [blockful-io/external-resolver#61]
Investigate the implementation of the [ENS' EVMGateway](https://github.com/ensdomains/evmgateway) to understand what is required to implement the L2 Offchain storage with Merkle Proof validation.

**Comment by pikonha** [comment]
We successfully ran the EVM Gateway locally gathering all the required contracts to be deployed both in the L1 and L2, as well as the implementations required to make our gateway capable of handling the Merkle Proof validation.
