### ISSUE TITLE
Domain Register UI Refinements

### ISSUE THREAD

**Issue by eduramme** [blockful-io/external-resolver#87]
#### Description
We need to refine the Domain Registration UI to enhance user experience and ensure alignment with the design specifications. The following tasks need to be completed:

- **Align Name Registration with Design Specs:**
  - Ensure that the Name Registration step in the Domain Register process fully matches the provided design specifications.
  - Verify all UI elements, fonts, colors, and spacing are consistent with the design.

- **Enable “Next Step” CTA Rules:**
  - Implement rules for enabling the “Next Step” Call-to-Action (CTA) button.
  - The “Next Step” CTA should only be clickable when all required fields are correctly filled out and valid.
  - Provide visual feedback or error messages for incomplete or invalid inputs.

- **Remove “Back” CTA from the First Step:**
  - Remove the “Back” button from the first step of the Domain Registration process.
  - Ensure the navigation flow is clear without the “Back” option on the initial step.

#### Acceptance Criteria
- [ ] The Name Registration step is visually aligned with the design specs.
- [x] The “Next Step” CTA is only active when all required fields are valid.
- [x] Clear error messages are displayed for invalid inputs.
- [x] The “Back” button is removed from the first step of the registration process.
- [x] User navigation through the Domain Registration steps is smooth and intuitive.

**Comment by FrancoAguzzi** [comment]
@eduramme PR approved with change requests 👍🏼🚀
