### ISSUE TITLE
[L2] Deploy contracts on testnet

### ISSUE THREAD

**Issue by LeonardoVieira1630** [blockful-io/external-resolver#92]
Now that the reading flow in working properly, it is necessary to deploy the contracts in the testnet. 
To complete the task, the contracts needed to be deployed and the flow tested. 

To deploy, use the scripts on the contracts folder (arbResolver.s.ts and arbResolverL2.s.ts). Also, the new urls of layer one and two will be the following:
L1 (Universal Resolver) - 0x499149A35c6Fb93aC2A235899cd41F1BEC478851
L2 (Arbitrum Resolver) - 0x047CCc01932Af96ED5CB0F41A4B79572341E3904

**Comment by pikonha** [comment]
Universal Resolver ENS deployment on Sepolia: 0xc8af999e38273d658be1b921b88a9ddf005769cc

[reference](https://github.com/ensdomains/ens-contracts/blob/staging/deployments/sepolia/UniversalResolver.json)
